services:
  - type: web
    runtime: static
    name: zinsendoktor-check
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
